databases:
  - name: edufundzdb
    plan: free
    databaseName: edufundz
    user: edufundz

services:
  - type: web
    plan: free
    name: edufundz
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn edufundz.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edufundzdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4